// Unit / regression tests against values produced by MATLAB R2025a and the
// original fitGaussian2D MEX (tests/reference_values.txt, generated by
// reference_tools/gen_unit_reference.m).
#include "cme/mt19937.hpp"
#include "cme/conv.hpp"
#include "cme/morphology.hpp"
#include "cme/stats.hpp"
#include "cme/fit_gaussian2d.hpp"
#include "cme/fit_gaussians2d.hpp"
#include "cme/point_source_detection.hpp"
#include "cme/gmm.hpp"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

static int g_fail = 0, g_pass = 0;
static double g_worstRel = 0.0;

static bool is_number(const std::string& s) {
    char* end = nullptr;
    std::strtod(s.c_str(), &end);
    return end && *end == '\0' && !s.empty();
}

struct Ref {
    std::map<std::string, std::vector<double>> v;
    std::map<std::string, std::vector<std::vector<double>>> rows;   // tcdf triples
    bool load(const std::string& path) {
        std::ifstream in(path);
        if (!in) return false;
        std::string line, pendingKey;
        while (std::getline(in, line)) {
            if (line.empty()) continue;
            std::istringstream ss(line);
            std::vector<std::string> tok;
            std::string t;
            while (ss >> t) tok.push_back(t);
            if (!pendingKey.empty()) {
                std::vector<double> d;
                for (auto& x : tok) d.push_back(std::strtod(x.c_str(), nullptr));
                v[pendingKey] = d;
                pendingKey.clear();
                continue;
            }
            std::string key;
            std::size_t i = 0;
            if (tok[0] == "gmm") { key = tok[0] + " " + tok[1] + " " + tok[2]; i = 3; }
            else { while (i < tok.size() && !is_number(tok[i])) { key += (key.empty() ? "" : " ") + tok[i]; ++i; } }
            std::vector<double> d;
            for (; i < tok.size(); ++i) d.push_back(std::strtod(tok[i].c_str(), nullptr));
            if (key == "tcdf") { rows[key].push_back(d); continue; }
            if (key == "win" || key == "img" || key == "padxt" || key == "gmm_data") { v[key + "_dims"] = d; pendingKey = key; continue; }
            if (tok[0] == "gmm" && tok.size() >= 10 && tok[2] == "NlogL") {
                // "gmm k NlogL x BIC y Iters z Conv w"
                v["gmm " + tok[1] + " NlogL"] = {std::strtod(tok[3].c_str(), nullptr)};
                v["gmm " + tok[1] + " BIC"] = {std::strtod(tok[5].c_str(), nullptr)};
                v["gmm " + tok[1] + " Iters"] = {std::strtod(tok[7].c_str(), nullptr)};
                v["gmm " + tok[1] + " Conv"] = {std::strtod(tok[9].c_str(), nullptr)};
                continue;
            }
            v[key] = d;
        }
        return true;
    }
    const std::vector<double>& get(const std::string& k) const {
        auto it = v.find(k);
        if (it == v.end()) { std::printf("MISSING reference key: %s\n", k.c_str()); std::exit(3); }
        return it->second;
    }
};

static void check(const char* name, double got, double ref, double atol = 1e-8, double rtol = 1e-6) {
    const bool bothNaN = std::isnan(got) && std::isnan(ref);
    const double diff = std::fabs(got - ref);
    const double tol = atol + rtol * std::fabs(ref);
    const bool ok = bothNaN || diff <= tol;
    if (!bothNaN && std::fabs(ref) > 1e-6) g_worstRel = std::max(g_worstRel, diff / std::fabs(ref));
    if (ok) ++g_pass;
    else { ++g_fail; std::printf("FAIL %s: got %.17g ref %.17g (diff %.3g)\n", name, got, ref, diff); }
}
static void check_vec(const char* name, const std::vector<double>& got, const std::vector<double>& ref, double atol = 1e-8, double rtol = 1e-6) {
    if (got.size() != ref.size()) { ++g_fail; std::printf("FAIL %s: size %zu vs %zu\n", name, got.size(), ref.size()); return; }
    for (std::size_t i = 0; i < got.size(); ++i) {
        char buf[128]; std::snprintf(buf, sizeof buf, "%s[%zu]", name, i);
        check(buf, got[i], ref[i], atol, rtol);
    }
}
static void check_eq(const char* name, long got, long ref) {
    if (got == ref) ++g_pass; else { ++g_fail; std::printf("FAIL %s: got %ld ref %ld\n", name, got, ref); }
}

int main(int argc, char** argv) {
    std::string refPath = argc > 1 ? argv[1] : "tests/reference_values.txt";
    Ref R;
    if (!R.load(refPath)) { std::printf("cannot open %s\n", refPath.c_str()); return 2; }

    // ---- RNG ----
    {
        cme::MatlabTwister r(1);
        const double ref[6] = {0.417022004702574, 0.7203244934421581, 0.00011437481734488664, 0.30233257263183977, 0.14675589081711304, 0.092338594768797799};
        for (int i = 0; i < 6; ++i) check("rand", r.rand(), ref[i], 0, 0);
        cme::MatlabTwister r2(1);
        const long e[5] = {5, 8, 1, 4, 2};
        for (int i = 0; i < 5; ++i) check_eq("randi", r2.randi(10), e[i]);
        cme::MatlabTwister r3(1);
        auto p = r3.randperm_k(100, 2);
        check_eq("randperm(100,2)[0]", p[0], 42); check_eq("randperm(100,2)[1]", p[1], 72);
    }
    // ---- stats ----
    check("norminv(0.975)", cme::norminv(0.975), R.get("norminv_0975")[0], 0, 1e-15);
    for (auto& row : R.rows["tcdf"]) check("tcdf", cme::tcdf(row[0], row[1]), row[2], 1e-16, 1e-12);
    check_eq("tcdf(0,0) is NaN", std::isnan(cme::tcdf(0, 0)) ? 1 : 0, static_cast<long>(R.get("tcdf_nan0")[0]));
    check("normcdf", cme::normcdf(0.3, 0.1, 1.7), R.get("normcdf")[0], 0, 1e-15);
    {
        std::vector<double> x(60), x2(60);
        for (int i = 1; i <= 60; ++i) { x[i - 1] = std::sin(i * 1.7) + 0.3 * std::cos(i * 0.4); x2[i - 1] = x[i - 1] * x[i - 1] * x[i - 1]; }
        auto mean_std = [](const std::vector<double>& a, double& m, double& s) {
            m = 0; for (double v : a) m += v; m /= a.size();
            s = 0; for (double v : a) s += (v - m) * (v - m); s = std::sqrt(s / (a.size() - 1));
        };
        double m, s;
        mean_std(x, m, s);
        auto ad = cme::adtest1_case3(x, m, s);
        check("adtest A2", ad.A2, R.get("adtest_A2")[0], 1e-12, 1e-12);
        check_eq("adtest H", ad.h, static_cast<long>(R.get("adtest_H")[0]));
        mean_std(x2, m, s);
        ad = cme::adtest1_case3(x2, m, s);
        check("adtest2 A2", ad.A2, R.get("adtest2_A2")[0], 1e-12, 1e-12);
        check_eq("adtest2 H", ad.h, static_cast<long>(R.get("adtest2_H")[0]));
    }
    // ---- Anderson-Darling decisions of the MEX on its own residuals ----
    for (const char* fn : {"tests/ad_reference.txt", "tests/ad_reference2.txt"}) {
        std::string path = fn;
        if (refPath.find("tests/") != std::string::npos) path = refPath.substr(0, refPath.find("tests/")) + fn;
        std::ifstream in(path);
        if (!in) { std::printf("skipping %s (not found)\n", path.c_str()); continue; }
        std::string l1, l2;
        long nCases = 0, bad = 0;
        while (std::getline(in, l1) && std::getline(in, l2)) {
            std::istringstream h(l1);
            int k, hAD; double mean, sd, rss;
            h >> k >> hAD >> mean >> sd >> rss;
            std::istringstream d(l2);
            std::vector<double> res; double v;
            while (d >> v) if (!std::isnan(v)) res.push_back(v);
            auto ad = cme::adtest_mex(res, mean, sd, 0.05);
            ++nCases;
            if ((ad.h ? 1 : 0) != hAD) { ++bad; std::printf("FAIL adtest_mex case %d: A2=%.6f got %d ref %d\n", k, ad.A2, ad.h, hAD); }
        }
        if (bad == 0) ++g_pass; else ++g_fail;
        std::printf("  adtest_mex: %ld/%ld MEX decisions reproduced (%s)\n", nCases - bad, nCases, fn);
    }
    // ---- padarrayXT ----
    {
        cme::ImageD a(3, 4);
        for (std::size_t i = 0; i < 12; ++i) a[i] = static_cast<double>(i + 1);
        cme::ImageD b = cme::padarrayXT_symmetric(a, 2);
        auto dims = R.get("padxt_dims");
        check_eq("padxt ny", static_cast<long>(b.ny()), static_cast<long>(dims[0]));
        check_eq("padxt nx", static_cast<long>(b.nx()), static_cast<long>(dims[1]));
        check_vec("padxt", b.vec(), R.get("padxt"), 0, 0);
    }
    // ---- conv2 sanity: valid conv of constant image with box kernel ----
    {
        cme::ImageD a(5, 6, 2.0);
        std::vector<double> u(3, 1.0);
        cme::ImageD c = cme::conv2_sep_valid(u, u, a);
        check_eq("conv ny", static_cast<long>(c.ny()), 3);
        check_eq("conv nx", static_cast<long>(c.nx()), 4);
        check("conv val", c(1, 1), 18.0, 0, 0);
    }
    // ---- locmax2d / bwconncomp ----
    {
        cme::ImageD a(7, 7, 0.0);
        a(3, 3) = 5; a(1, 1) = 3; a(1, 2) = 3;   // plateau at (1,1),(1,2) must be suppressed
        cme::ImageD lm = cme::locmax2d(a, 3);
        check("locmax centre", lm(3, 3), 5, 0, 0);
        check("locmax plateau", lm(1, 1) + lm(1, 2), 0, 0, 0);
        cme::ImageU8 bw(5, 5, 0);
        bw(0, 0) = 1; bw(1, 1) = 1; bw(4, 4) = 1; bw(3, 4) = 1; bw(0, 4) = 1;
        auto cc = cme::bwconncomp8(bw);
        check_eq("bwconncomp n", static_cast<long>(cc.numObjects), 3);
        check_eq("bwconncomp first comp size", static_cast<long>(cc.pixelIdxList[0].size()), 2);
    }
    // ---- fitGaussian2D vs MEX ----
    {
        auto dims = R.get("win_dims");
        const int n = static_cast<int>(std::sqrt(dims[0]));
        cme::ImageD win(n, n);
        const auto& wv = R.get("win");
        for (int i = 0; i < n * n; ++i) win[i] = wv[i];
        double mn = win.minval(), mx = win.maxval();
        std::array<double, 5> init = {0, 0, mx - mn, 1.5, mn};
        const char* modes[] = {"xyAc", "xyasc", "Ac", "xyac"};
        for (const char* m : modes) {
            cme::FitResult f = cme::fitGaussian2D(win, init, m);
            std::string k = std::string("fit ") + m + " ";
            check_vec((k + "prm").c_str(), std::vector<double>(f.prm.begin(), f.prm.end()), R.get(k + "prm"));
            check_vec((k + "prmStd").c_str(), f.prmStd, R.get(k + "prmStd"));
            auto res = R.get(k + "res");
            check((k + "res.mean").c_str(), f.mean, res[0], 1e-10, 0);
            check((k + "res.std").c_str(), f.std, res[1]);
            check((k + "res.RSS").c_str(), f.RSS, res[2]);
            check_eq((k + "res.hAD").c_str(), f.hAD, static_cast<long>(res[3]));
            std::printf("  %-6s iters=%d status=%d\n", m, f.iterations, f.status);
        }
        cme::ImageD win2 = win;
        for (int y = 0; y < 3; ++y) for (int x = 0; x < 4; ++x) win2(y, x) = std::nan("");
        win2(9, 11) = std::nan("");
        cme::FitResult f = cme::fitGaussian2D(win2, init, "xyAc");
        check_vec("fitnan prm", std::vector<double>(f.prm.begin(), f.prm.end()), R.get("fitnan xyAc prm"));
        check_vec("fitnan prmStd", f.prmStd, R.get("fitnan xyAc prmStd"));
        auto res = R.get("fitnan xyAc res");
        check("fitnan std", f.std, res[1]); check("fitnan RSS", f.RSS, res[2]);
        check_eq("fitnan hAD", f.hAD, static_cast<long>(res[3]));
        // x/y convention: spot shifted along x (columns) only
        cme::ImageD win3(n, n);
        const int w = n / 2;
        for (int xx = 0; xx < n; ++xx) for (int yy = 0; yy < n; ++yy) {
            const double X = xx - w, Y = yy - w;
            const double noise = 4 * std::sin(1000 * (X * 13 + Y)) + 2 * std::cos(37 * X * Y);
            win3(yy, xx) = 100 * std::exp(-((X - 1.2) * (X - 1.2) + Y * Y) / (2 * 1.5 * 1.5)) + 50 + noise;
        }
        f = cme::fitGaussian2D(win3, init, "xyAc");
        check_vec("fitx prm", std::vector<double>(f.prm.begin(), f.prm.end()), R.get("fitx xyAc prm"));
    }
    // ---- fitGaussians2D / pointSourceDetection on synthetic image ----
    {
        auto dims = R.get("img_dims");
        cme::ImageD img(static_cast<std::size_t>(dims[0]), static_cast<std::size_t>(dims[1]));
        const auto& iv = R.get("img");
        for (std::size_t i = 0; i < img.size(); ++i) img[i] = iv[i];
        cme::PStruct ps = cme::fitGaussians2D(img, {20, 36}, {16, 28}, {}, {1.5, 1.5}, {}, "xyAc");
        check_vec("fg2d x", ps.x, R.get("fg2d x")); check_vec("fg2d y", ps.y, R.get("fg2d y"));
        check_vec("fg2d A", ps.A, R.get("fg2d A")); check_vec("fg2d c", ps.c, R.get("fg2d c"));
        check_vec("fg2d A_pstd", ps.A_pstd, R.get("fg2d A_pstd")); check_vec("fg2d sigma_r", ps.sigma_r, R.get("fg2d sigma_r"));
        check_vec("fg2d pval_Ar", ps.pval_Ar, R.get("fg2d pval_Ar")); check_vec("fg2d mask_Ar", ps.mask_Ar, R.get("fg2d mask_Ar"), 0, 0);
        check_eq("fg2d hval_AD0", ps.hval_AD[0], static_cast<long>(R.get("fg2d hval_AD")[0]));
        cme::PStruct pa = cme::fitGaussians2D(img, {20, 36}, {16, 28}, {}, {1.5, 1.5}, {}, "Ac");
        check_vec("fg2dAc A", pa.A, R.get("fg2dAc A")); check_vec("fg2dAc c", pa.c, R.get("fg2dAc c"));
        check_vec("fg2dAc pval_Ar", pa.pval_Ar, R.get("fg2dAc pval_Ar"), 1e-300, 1e-6);

        cme::PSDDebug dbg;
        cme::PSDResult r = cme::pointSourceDetection(img, 1.5, cme::PSDOptions(), &dbg);
        check_eq("psd n", static_cast<long>(r.pstruct.size()), static_cast<long>(R.get("psd n")[0]));
        check_vec("psd x", r.pstruct.x, R.get("psd x")); check_vec("psd y", r.pstruct.y, R.get("psd y"));
        check_vec("psd A", r.pstruct.A, R.get("psd A")); check_vec("psd c", r.pstruct.c, R.get("psd c"));
        check_vec("psd RSS", r.pstruct.RSS, R.get("psd RSS"));
        long ms = 0; for (auto v : r.mask.vec()) ms += v;
        check_eq("psd masksum", ms, static_cast<long>(R.get("psd masksum")[0]));
        auto lg = R.get("psd loG");
        check("loG(1,1)", dbg.imgLoG(0, 0), lg[0], 1e-10, 1e-10);
        check("loG(16,20)", dbg.imgLoG(15, 19), lg[1], 1e-10, 1e-10);
        check("loG(40,50)", dbg.imgLoG(39, 49), lg[2], 1e-10, 1e-10);
    }
    // ---- gmdistribution.fit ----
    {
        const auto& xg = R.get("gmm_data");
        cme::MatlabTwister rng(1);
        for (int k = 1; k <= 3; ++k) {
            cme::GmmResult g = cme::gmdistribution_fit_1d(xg, k, rng, 200);
            std::string key = "gmm " + std::to_string(k) + " ";
            check_vec((key + "mu").c_str(), g.mu, R.get(key + "mu"), 1e-10, 1e-10);
            check_vec((key + "Sigma").c_str(), g.Sigma, R.get(key + "Sigma"), 1e-10, 1e-10);
            check_vec((key + "P").c_str(), g.PComponents, R.get(key + "P"), 1e-10, 1e-10);
            check((key + "NlogL").c_str(), g.NlogL, R.get(key + "NlogL")[0], 1e-10, 1e-12);
            check((key + "BIC").c_str(), g.BIC, R.get(key + "BIC")[0], 1e-10, 1e-12);
            check_eq((key + "Iters").c_str(), g.iters, static_cast<long>(R.get(key + "Iters")[0]));
            check_eq((key + "Conv").c_str(), g.converged, static_cast<long>(R.get(key + "Conv")[0]));
        }
        check("rand after gmm", rng.rand(), R.get("rand_after")[0], 0, 0);
    }
    std::printf("%d passed, %d failed (worst relative deviation %.3g)\n", g_pass, g_fail, g_worstRel);
    return g_fail == 0 ? 0 : 1;
}
